services:
  play21:
    build: .
    ports:
      - "5521:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./media:/app/media
      - ./data:/app/data
    devices:
      - /dev/dri:/dev/dri
    environment:
      - ALLOWED_DOMAINS=* (Default behavior)
#     - ALLOWED_DOMAINS=https://my-site.com,https://another-site.org
#     - ALLOWED_DOMAINS=*.example.com,*.internal.net
    restart: unless-stopped